### PR TITLE
Update dependencies to React 16.2, OnsenUI 2.9.2, React OnsenUI 1.10

### PR DESCRIPTION
**Pull request by karlvr**
I've tried to do this upgrade with the minimum of changes to the source code.

A summary of the change:
* `main.js` gets its React components converted to `Component` subclasses
* `key` props have been added everywhere to fix the React warnings about missing `key`s in lists
* Deprecated usage of `<Input type="radio|checkbox">` has been changed to `<Radio|Checkbox>`
* Deprecated usage of `<Splitter isSwipeable>` changed to `swipeable`.

The project now runs without warnings, and is using the latest releases of everything.

### CODE REVIEW

**Comment by karlvr** [comment]
Note that `css/*` and `dist.js` have been updated as well. As these are actually built products, perhaps we could add them to a `.gitignore` and remove them from the repository? I have updated them all in a separate "Built products" commit so you can more easily separate out the important changes!

**Comment by karlvr** [comment]
This PR should address #5

**Comment by karlvr** [comment]
I'm quite new to Onsen... perhaps the `key` handling should be internalised as part of `react-onsenui` and made more automatic in there? The changes I've made here work, so I guess they're a good demo of what you need to do with React 16.2 and react-onsenui 1.10 today.

**Comment by asialgearoid** [comment]
This is great, thanks so much for this PR, @karlvr! :+1:

**Comment by karlvr** [comment]
You’re most welcome, thank you.

**Pull request merged**
